### ISSUE TITLE
Page crashes with RESULT_CODE_INVALID_CMDLINE_URL

### ISSUE THREAD

**Issue by zhigang1992** [alo7/rebirth#6]
When rebuilding docker with latest version chrome(81)

The recording often crash with `RESULT_CODE_INVALID_CMDLINE_URL`,

It does not crash without starting to record.

It works after switch back to chrome 80.

**Comment by BlackHole1** [comment]
Thanks for your feedback, these days I will see where is the problem

**Comment by zhigang1992** [comment]
Awesome, thanks. Here is a reproducible link.

https://tinyurl.com/y9c3jko9

**Comment by BlackHole1** [comment]
Okay received, I fix this problem by this Sunday at the latest

**Comment by BlackHole1** [comment]
open the chrome debug log by adding: `--enable-logging --v=1` to the chrome startup parameters. I found that in the moment of crash, there is such a section in the debug log:

```log
[154:161:0611/124700.463365:FATAL:memory.cc(38)] Out of memory. size=3796992
```

Later I went into the investigation and found that it was caused by too little `/dev/shm` capacity

But this is strange because I added `--disable-dev-shm-usage`, Chrome should use `/tmp` instead of continuing to use `/dev/shm`

I haven't found the reason why `--disable-dev-shm-usage` is invalid, but you can add `--shm-size=1g` to solve this problem when `docker run` the container.

It looks like this:

```bash
docker run -dit -P --name rebirth_alo7 -v `pwd`/rebirth_alo7/logs:/etc/www/logs -v `pwd`/rebirth_alo7/video:/root/Downloads  -e MATERIAL_URL="https://tinyurl.com/y9c3jko9" --shm-size=1g alo7docker/rebirth
```
